apiVersion: v1
data:
  QUARKUS_PROFILE: stg
kind: ConfigMap
metadata:
  name: quarkus-profile
---
apiVersion: v1
data:
  application.properties: |-
    %local.kafka.bootstrap.servers=localhost:9098
    %dev.kafka.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    %stg.kafka.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    %prod.kafka.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    
    %local.quarkus.http.port=8080
    %dev.quarkus.http.port=8080
    %stg.quarkus.http.port=8080
    %prod.quarkus.http.port=8080
    quarkus.log.level=INFO
    
    mp.messaging.outgoing.java_generator_kafka_to_raw.topic=quarkus-pubsub-raw
    #mp.messaging.outgoing.java_generator_kafka_to_raw.key.serializer=org.apache.kafka.common.serialization.StringSerializer
    #mp.messaging.outgoing.java_generator_kafka_to_raw.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    %local.mp.messaging.outgoing.java_generator_kafka_to_raw.bootstrap.servers=localhost:9098
    %dev.mp.messaging.outgoing.java_generator_kafka_to_raw.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    %stg.mp.messaging.outgoing.java_generator_kafka_to_raw.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    %prod.mp.messaging.outgoing.java_generator_kafka_to_raw.bootstrap.servers=diaz-cluster-kafka-brokers.strimzi.svc.cluster.local:9098
    
    %local.stream.msg.in.mil=5000
    %dev.stream.msg.in.mil=5000
    %stg.stream.msg.in.mil=1
    %prod.stream.msg.in.mil=1
    
    quarkus.container-image.build=true
    #quarkus.native.reuse-existing=true
    #quarkus.container-image.group=modernizedmicroserviceacr.azurecr.io
    quarkus.container-image.name=quarkus-sf-source
    quarkus.container-image.tag=nonnative
    quarkus.jib.ports=8080
    #quarkus.container-image.push=true
    #quarkus.jib.jvm-entrypoint=/opt/jboss/container/java/run/run-java.sh
    #quarkus.jib.native-entrypoint=/opt/jboss/container/java/run/run-java.sh
    #quarkus.jib.jvm-entrypoint=java,-cp,.,-jar,/home/jboss/quarkus-run.jar
    #quarkus.jib.native-entrypoint=java,-cp,.,-jar,/home/jboss/quarkus-run.jar
    #quarkus.jib.jvm-additional-arguments="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    #quarkus.jib.jvm-additional-arguments="-XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
kind: ConfigMap
metadata:
  name: quarkus-sf-source-application-properties