{
  "apiVersion": "argoproj.io/v1alpha1",
  "kind": "Application",
  "metadata": {
    "name": "{{ .Values.metadata.name }}-prod",
    "namespace": "{{ .Values.metadata.namespace }}",
    "finalizers": [
      "resources-finalizer.argocd.argoproj.io"
    ],
    "annotations": {
      "notifications.argoproj.io/subscribe.on-sync-succeeded.slack": "#devops-argocd-prod"
    }
  },
  "spec": {
    "project": "{{ .Values.spec.projectProd }}",
    "source": {
      "path": "{{ .Values.spec.source.pathProd }}",
      "repoURL": "{{ .Values.spec.source.repoDevURL }}{{ .Values.spec.source.repoGit }}",
      "targetRevision": "{{ .Values.spec.source.targetRevision }}"
    },
    "destination": {
      "namespace": "{{ .Values.metadata.name }}-prod",
      "server": "{{ .Values.spec.destination.server }}"
    },
    "syncPolicy": {
      "automated": {
        "selfHeal": true
      }
    }
  }
}
