apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-sf-source
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: quarkus-sf-source
    template:
      metadata:
        labels:
          app.kubernetes.io/name: quarkus-sf-source
      spec:
        containers:
          - env:
              - name: JAVA_INITIAL_MEM_RATIO
                value: '50'
              - name: JAVA_MAX_MEM_RATIO
                value: '80'
              - name: JAVA_APP_DIR
                value: "/deployments"
            envFrom:
              - configMapRef:
                  name: quarkus-sf-source-jar
              - configMapRef:
                  name: java-app-dir
              - configMapRef:
                  name: quarkus-http-port
              - configMapRef:
                  name: quarkus-profile
            image: modernizedmicroserviceacr.azurecr.io/quarkus-sf-source:nonnative
            imagePullPolicy: IfNotPresent
            name: quarkus-sf-source
            ports:
              - containerPort: 8080
                protocol: TCP
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: "/deployments/config"
                name: volume-application-properties
              - mountPath: "/mnt"
                name: volume-prometheus-conf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: quarkus-sf-source-application-properties
            name: volume-application-properties
          - configMap:
              defaultMode: 420
              name: prometheus-conf
            name: volume-prometheus-conf
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-sf-raw
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: quarkus-sf-raw
    template:
      metadata:
        labels:
          app.kubernetes.io/name: quarkus-sf-raw
      spec:
        containers:
          - env:
              - name: JAVA_INITIAL_MEM_RATIO
                value: '50'
              - name: JAVA_MAX_MEM_RATIO
                value: '80'
              - name: JAVA_APP_DIR
                value: "/deployments"
            envFrom:
              - configMapRef:
                  name: quarkus-sf-raw-jar
              - configMapRef:
                  name: java-app-dir
              - configMapRef:
                  name: quarkus-http-port
              - configMapRef:
                  name: quarkus-profile
            image: modernizedmicroserviceacr.azurecr.io/quarkus-sf-raw:nonnative
            imagePullPolicy: IfNotPresent
            name: quarkus-sf-raw
            ports:
              - containerPort: 8080
                protocol: TCP
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: "/deployments/config"
                name: volume-application-properties
              - mountPath: "/home/jboss/sf/config"
                name: volume-snowflake-properties
              - mountPath: "/mnt"
                name: volume-prometheus-conf
              - mountPath: "/home/jboss/sf/keys"
                name: volume-application-keys
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: quarkus-sf-raw-application-properties
            name: volume-application-properties
          - configMap:
              defaultMode: 420
              name: quarkus-sf-raw-snowflake-properties
            name: volume-snowflake-properties
          - configMap:
              defaultMode: 420
              name: prometheus-conf
            name: volume-prometheus-conf
          - secret:
              defaultMode: 420
              secretName: rsa-key-dataintegration-p8
            name: volume-application-keys
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-sf-normalize
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: quarkus-sf-normalize
    template:
      metadata:
        labels:
          app.kubernetes.io/name: quarkus-sf-normalize
      spec:
        containers:
          - env:
              - name: JAVA_INITIAL_MEM_RATIO
                value: '50'
              - name: JAVA_MAX_MEM_RATIO
                value: '80'
              - name: JAVA_APP_DIR
                value: "/deployments"
            envFrom:
              - configMapRef:
                  name: quarkus-sf-normalize-jar
              - configMapRef:
                  name: java-app-dir
              - configMapRef:
                  name: quarkus-http-port
              - configMapRef:
                  name: quarkus-profile
            image: modernizedmicroserviceacr.azurecr.io/quarkus-sf-normalize:nonnative
            imagePullPolicy: IfNotPresent
            name: quarkus-sf-normalize
            ports:
              - containerPort: 8080
                protocol: TCP
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: "/deployments/config"
                name: volume-application-properties
              - mountPath: "/home/jboss/sf/config"
                name: volume-snowflake-properties
              - mountPath: "/mnt"
                name: volume-prometheus-conf
              - mountPath: "/home/jboss/sf/keys"
                name: volume-application-keys
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: quarkus-sf-normalize-application-properties
            name: volume-application-properties
          - configMap:
              defaultMode: 420
              name: quarkus-sf-normalize-snowflake-properties
            name: volume-snowflake-properties
          - configMap:
              defaultMode: 420
              name: prometheus-conf
            name: volume-prometheus-conf
          - secret:
              defaultMode: 420
              secretName: rsa-key-dataintegration-p8
            name: volume-application-keys
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-sf-tokenize
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: quarkus-sf-tokenize
    template:
      metadata:
        labels:
          app.kubernetes.io/name: quarkus-sf-tokenize
      spec:
        containers:
          - env:
              - name: JAVA_INITIAL_MEM_RATIO
                value: '50'
              - name: JAVA_MAX_MEM_RATIO
                value: '80'
              - name: JAVA_APP_DIR
                value: "/deployments"
            envFrom:
              - configMapRef:
                  name: quarkus-sf-tokenize-jar
              - configMapRef:
                  name: java-app-dir
              - configMapRef:
                  name: quarkus-http-port
              - configMapRef:
                  name: quarkus-profile
            image: modernizedmicroserviceacr.azurecr.io/quarkus-sf-tokenize:nonnative
            imagePullPolicy: IfNotPresent
            name: quarkus-sf-tokenize
            ports:
              - containerPort: 8080
                protocol: TCP
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: "/deployments/config"
                name: volume-application-properties
              - mountPath: "/home/jboss/sf/config"
                name: volume-snowflake-properties
              - mountPath: "/mnt"
                name: volume-prometheus-conf
              - mountPath: "/home/jboss/sf/keys"
                name: volume-application-keys
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: quarkus-sf-tokenize-application-properties
            name: volume-application-properties
          - configMap:
              defaultMode: 420
              name: quarkus-sf-tokenize-snowflake-properties
            name: volume-snowflake-properties
          - configMap:
              defaultMode: 420
              name: prometheus-conf
            name: volume-prometheus-conf
          - secret:
              defaultMode: 420
              secretName: rsa-key-dataintegration-p8
            name: volume-application-keys
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''
